from typing import Optional

import torch
from torch.nn import L1Loss

from .AbstractLoss import AbstractLoss

class GeneratorLoss(AbstractLoss):
    def __init__(self, 
                 _metric_name: str, 
                reconstruction_loss: Optional[torch.tensor] = L1Loss()
                ):
        """
        :param reconstruction_loss: The image reconstruction loss, 
        defaults to L1Loss(reduce=False)
        :type reconstruction_loss: torch.tensor
        """
        
        super().__init__(_metric_name)

        self._reconstruction_loss = reconstruction_loss

    def forward(self, 
                discriminator_probs: torch.tensor,
                fake_images: torch.tensor, 
                real_images: torch.tensor,
                epoch: Optional[int] = None                
                ):
        """
        Computes the loss for the GaN generator.

        :param discriminator_probs: The probabilities of the discriminator for the fake images being real.
        :type discriminator_probs: torch.tensor
        :param fake_images: The fake images generated by the generator.
        :type fake_images: torch.tensor
        :param real_images: The real images.
        :type real_images: torch.tensor
        :param epoch: The current epoch number. 
        Used for a smoothing weight for the adversarial loss component 
        :type epoch: int
        """

        # Adversarial loss
        adversarial_loss = -torch.mean(discriminator_probs)
        if epoch is not None:
            adversarial_loss = 0.01 * adversarial_loss/(epoch + 1)

        image_loss = self._reconstruction_loss(fake_images, real_images)
        
        return adversarial_loss + image_loss.mean()